alter table chat_messages
    add column status varchar(32) not null default 'COMPLETED',
    add column request_id varchar(128),
    add column model varchar(256),
    add column prompt_tokens integer,
    add column completion_tokens integer,
    add column generation_duration_ms bigint,
    add column error_message text,
    add column updated_at timestamptz not null default now(),
    add column sequence_number bigint generated by default as identity;

create unique index idx_chat_messages_request_role
    on chat_messages(chat_id, request_id, role)
    where request_id is not null;

create unique index idx_chat_messages_chat_sequence
    on chat_messages(chat_id, sequence_number);

create table if not exists spring_ai_chat_memory (
    conversation_id varchar(128) not null,
    content text not null,
    type varchar(10) not null check (type in ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    "timestamp" timestamp not null,
    sequence_id bigint not null
);

create index if not exists idx_spring_ai_chat_memory_timestamp
    on spring_ai_chat_memory(conversation_id, "timestamp");

create index if not exists idx_spring_ai_chat_memory_sequence
    on spring_ai_chat_memory(conversation_id, sequence_id);
